apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/stateful-storage"
    type: Directory
