apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-gateway
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheusgateway"
