apiVersion: v1
kind: Pod
metadata:
  name: connect-mysql
  labels:
    app: connect-mysql
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args: ["while : ; do sleep 1 ; done ;"]
     
