apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-processor
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/paymentprocessor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-processor-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M
