apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasapp
  labels:
    app: wasapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wasapp
  template:
    metadata:
      labels:
        app: wasapp
    spec:
      volumes:
      - name: wasapp-volume
        emptyDir: {}
      containers:
        - name: wasapp
          image: myregistry.localhost/wasapp
          imagePullPolicy: Always
          ports:
          - containerPort: 9080
          - containerPort: 9443
          volumeMounts:
          - name: wasapp-volume
            mountPath: /opt/ibm/wlp/usr/servers/wasapp/dropins
#      imagePullSecrets:
#      - name: docker-registry
      initContainers:
      - name: git-init # Step 1: Downloading (cloning) Java projects with Git 
        image: myregistry.localhost/alpine
        command: ["/bin/sh", "-c"]
        args: ["ls /home/bogdan/ ; mkdir /home/bogdan/my-app/"]
        volumeMounts:
        - name: wasapp-volume
          mountPath: "/home/bogdan/my-app"
