apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: wasapp-repo
  namespace: bogdan
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/zbogdan7/wasapp
