apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: middleware-task
spec:
  params:
  - name: committer
    type: string
    default: "No message"
  steps:
  - name: first
    image: alpine
    script: |
      echo "First time message is $(params.committer)"
  - name: second
    image: alpine
    script: |
      echo "Second time message is $(params.committer)"
