apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-processor-pipeline
  namespace: bogdan
spec:
  params:
  - name: committer
    type: string
    default: "DefaultCommitter"
  resources:
  - name: backend-git
    type: git
  - name: frontend-git
    type: git
  - name: wasapp-image
    type: image
  - name: wasapp-front
    type: image
  tasks:
  - name: backend-deploy
    taskRef:
      name: deploy-backend-task
    resources:
      inputs:
      - name: payment-processor-backend
        resource: backend-git
      outputs:
      - name: wasapp-piped
        resource: wasapp-image
  - name: frontend-deploy
    taskRef: 
      name: deploy-frontend-task
    runAfter:
    - backend-deploy
    resources:
      inputs:
      - name: payment-processor-frontend
        resource: frontend-git
      outputs:
      - name: wasapp-frontend
        resource: wasapp-front
  - name: middleware-task
    taskRef: 
      name: middleware-task
    runAfter:
    - frontend-deploy
    params:
    - name: committer
      value: $(params.committer)
