apiVersion: v1
kind: Service
metadata:
  name: payment-processor-backend
  labels:
    app: payment-processor-backend
spec:
  type: ClusterIP
  selector:
    app: payment-processor-backend
  ports:
    - name: was-lib
      port: 9080
      targetPort: 9080
    - name: was-lib-sec
      port: 9443
      targetPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor-backend-external
  labels:
    app: payment-processor-backend
spec:
  type: NodePort
  selector:
    app: payment-processor-backend
  ports:
  - name: was-lib
    port: 9080
    targetPort: 9080
    nodePort: 32555
  - name: was-lib-sec
    port: 9443
    targetPort: 9443
