apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-processor-storage
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.0.107
    path: "/home/worker1/shared/mysqldb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-processor-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
