apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: bogdan
spec:
  params:
  - name: dockerfile
    default: $(resources.inputs.docker-source.path)/Dockerfile
    type: string
  - name: pathContext
    type: string
    default: $(resources.inputs.docker-source.path)
  resources:
    inputs:
    - name: docker-source
      type: git
    outputs:
    - name: builtImage
      type: image
  steps:
  - name: build-and-push
    image: buildah/buildah
    securityContext:
      privileged: true
    script: |
      buildah bud --tag=$(resources.outputs.builtImage.url) --file=$(params.dockerfile) --tls-verify=false $(params.pathContext)
      buildah push --tls-verify=false $(resources.outputs.builtImage.url)    
