apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.0.141
    path: /home/worker1/shared/mysql-db-statefulset
