apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  serviceName: mysql-db
  selector:
    matchLabels:
      app: mysql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-db-pvc
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
  volumeClaimTemplates:
  - metadata:
      name: mysql-db-pvc
    spec:
      accessModes:
      - ReadWriteOnce
#      storageClassName: ocs-storagecluster-ceph-rbd
      resources:
        requests:
          storage: 1Gi
