apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
  labels:
    type: nfs
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.0.141
    path: "/home/worker1/shared/private-registry"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage-claim
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
