apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-frontend-task
  namespace: bogdan
spec:
  resources:
    inputs:
    - name: payment-processor-frontend
      type: git
    outputs:
    - name: wasapp-frontend
      type: image
  params:
  - name: dockerfile
    type: string
    default: $(resources.inputs.payment-processor-frontend.path)/Dockerfile
  - name: pathContext
    type: string
    default: $(resources.inputs.payment-processor-frontend.path)
  steps:
  - name: build
    image: buildah/buildah
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    script: |
      buildah bud --tag=$(resources.outputs.wasapp-frontend.url) --file=$(params.dockerfile) --tls-verify=false $(params.pathContext)
      buildah push --tls-verify=false $(resources.outputs.wasapp-frontend.url)
  - name: deploy
    image: bitnami/kubectl
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - name: creds
      mountPath: /creds
    script: |
      ls -alt /creds
      kubectl config set-cluster my-cluster --server=https://192.168.0.131:6443 --embed-certs --certificate-authority=/creds/ca.crt
      kubectl config set-credentials bogdan --token=$(cat /creds/token)
      kubectl config set-context my-context --cluster=my-cluster --user=bogdan --namespace=bogdan
      kubectl config use-context my-context
      
      result=$(kubectl get all -l app=payment-processor-frontend)
      if [ -z "$result" ] ; then
        kubectl apply -f $(params.pathContext)/deployment.yaml
      else
        kubectl rollout restart deployment payment-processor-frontend
      fi
  volumes:
  - name: creds
    secret:
      secretName: default-token-mqfmg
