apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-space
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/pipeline-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
#  hostPath:
#    path: "/mnt/pipelinestorage"
