apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-0
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.0.141
    path: "/home/worker1/shared/vault-storage"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: vault-storage-claim
#  namespace: bogdan
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
