apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8300
        env:
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8300"
        - name: VAULT_DEV_ROOT_TOKEN
          value: "admin_123"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
          privileged: true
