apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-credentials
  namespace: bogdan
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: bogdan_123
