apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  labels:
    type: nfs
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 172.18.47.242
    path: "/home/worker01/shared/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: bogdan
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
