apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-backend-task
  namespace: bogdan
spec:
  resources:
    inputs:
    - name: payment-processor-backend
      type: git
    outputs:
    - name: wasapp-piped
      type: image
  params:
  - name: dockerfile
    type: string
    default: $(resources.inputs.payment-processor-backend.path)/Dockerfile
  - name: pathContext
    type: string 
    default: $(resources.inputs.payment-processor-backend.path)
  steps:
  - name: build
    image: 'maven:3.6.3-openjdk-11'
    imagePullPolicy: IfNotPresent
    name: build
    script: |
      mvn clean package --file /workspace/payment-processor-backend
  - name: push
    image: buildah/buildah
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    script: |
      buildah bud --tag=$(resources.outputs.wasapp-piped.url) --file=$(params.dockerfile) $(params.pathContext)
      buildah push --tls-verify=false $(resources.outputs.wasapp-piped.url)
  - name: deploy
    image: bitnami/kubectl
    securityContext:
      privileged: true
    volumeMounts:
    - name: creds
      mountPath: /creds
    script: |
      kubectl get all

      result=$(kubectl get all -l app=payment-processor)

      if [ -z "$result" ] ; then
        kubectl apply -f $(params.pathContext)/deployment.yaml
      else
        kubectl rollout restart deployment payment-processor
      fi
  volumes:
  - name: creds
    secret:
      secretName: default-token-mqfmg  
